name: Firebase Deploy
on:
  push:
    branches:
      - main

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v2
        with:
          submodules: true 
          fetch-depth: 0

      - name: Hugo setup
        uses: peaceiris/actions-hugo@v2.4.12
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        with:
          hugo-version: latest
          extended: false

      - name: Build
        run: hugo

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
